---
- name: Common | Update apt cache
  sudo: yes
  apt: update-cache=yes
  tags: common

- name: Common | Update language
  sudo: yes
  apt: pkg=language-pack-en
  tags: common

- name: Common | install git
  sudo: yes
  apt: pkg=git-core
  tags: common